apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemisAddress
metadata:
  name: mytopic-queue1
  namespace: andy-broker
spec:
  addressName: mytopic
  removeFromBrokerOnDelete: true
  applyToCrNames:
    - broker
  queueConfiguration:
    autoCreateAddress: false
    durable: true
    enabled: true
  queueName: mytopic-queue1
  routingType: multicast