apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 2
    image: quay.io/ataylor/activemq-artemis-broker-kubernetes:latest
    initImage: quay.io/ataylor/artemis-init-container:latest
    clustered: true
  brokerProperties:
    - "clusterConfigurations.my-cluster.producerWindowSize=-1"
    - "clusterConfigurations.my-cluster.retryInterval=1234"
  console:
    expose: true
  acceptors:
    - name: "artemis"
      port: 61617
      protocols: core
