apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 1
    image: uberman:5000/artemiscloud/activemq-artemis-broker-kubernetes:latest
    initImage: uberman:5000/artemiscloud/artemis-init-container:latest
    clustered: false
  brokerProperties:
    securityEnabled: "false"
    rejectEmptyValidatedUser: "true"
    populateValidatedUser: "true"
    threadPoolMaxSize: "25"
  console:
    expose: true
  acceptors:
    - name: "artemis"
      port: 61617
      protocols: core
