apiVersion: v1
kind: Service
metadata:
  name: wildfly-demo-ping-service
  annotations:
    description: The JGroups ping service for clustering discovery.
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: wildfly-clustering-demo