apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: targetbroker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 1
    image: quay.io/ataylor/activemq-artemis-broker-kubernetes:latest
    initImage: quay.io/ataylor/artemis-init-container:latest
    clustered: true
  brokerProperties:
   - "AMQPConnections.target.uri=tcp://sourcebroker-ss-0.sourcebroker-hdls-svc.activemq-artemis-operator.svc.cluster.local:61617"
   - "AMQPConnections.target.retryInterval=5000"
   - "AMQPConnections.target.reconnect-attempts=-1"
   - "AMQPConnections.target.user=admin"
   - "AMQPConnections.target.password=password"
   - "AMQPConnections.target.autoStart=true"
   - "AMQPConnections.target.connectionElements.mirror.type=MIRROR"
   - "AMQPConnections.target.connectionElements.mirror.messageAcknowledgements=true"
   - "AMQPConnections.target.connectionElements.mirror.queueCreation=true"
   - "AMQPConnections.target.connectionElements.mirror.queueRemoval=true"
  console:
    expose: true
  acceptors:
    - name: "artemis"
      port: 61617
      protocols: core
